#!/bin/bash
Test file 
file 2
file 3 
this is sample file
merge 6 line and 
7th line 
file 2
file 3 
This is sample file
11th line and 
12th line and 
test
Test
File
This is 16th line
This is 17th line
This is 18th line
This is 19th line
